### ISSUE TITLE
"gcc can't create executables" on Leo PPC

### ISSUE THREAD

**Issue by chdiza** [mistydemeo/tigerbrew#349] opened 2015-08-27 17:24 UTC
When building stuff (the build of readline that's auto-triggered by trying to pour the leopard bottle for ruby, for instance), I get failure near the beginning of configuration with the message in the title.

It also says "see config.log for details".  Here is what appears to be the relevant portion:

```
configure:3078: checking for C compiler version
configure:3087: gcc-4.2 --version >&5
/Applications/z/tigerbrew/Library/ENV/4.3/gcc-4.2:9:in `require': no such file to load -- extend/string (LoadError)
	from /Applications/z/tigerbrew/Library/ENV/4.3/gcc-4.2:9
configure:3098: $? = 1
configure:3087: gcc-4.2 -v >&5
/Applications/z/tigerbrew/Library/ENV/4.3/gcc-4.2:9:in `require': no such file to load -- extend/string (LoadError)
	from /Applications/z/tigerbrew/Library/ENV/4.3/gcc-4.2:9
configure:3098: $? = 1
configure:3087: gcc-4.2 -V >&5
/Applications/z/tigerbrew/Library/ENV/4.3/gcc-4.2:9:in `require': no such file to load -- extend/string (LoadError)
	from /Applications/z/tigerbrew/Library/ENV/4.3/gcc-4.2:9
configure:3098: $? = 1
configure:3087: gcc-4.2 -qversion >&5
/Applications/z/tigerbrew/Library/ENV/4.3/gcc-4.2:9:in `require': no such file to load -- extend/string (LoadError)
	from /Applications/z/tigerbrew/Library/ENV/4.3/gcc-4.2:9
configure:3098: $? = 1
configure:3118: checking whether the C compiler works
configure:3140: gcc-4.2    conftest.c  >&5
/Applications/z/tigerbrew/Library/ENV/4.3/gcc-4.2:9:in `require': no such file to load -- extend/string (LoadError)
	from /Applications/z/tigerbrew/Library/ENV/4.3/gcc-4.2:9
configure:3144: $? = 1
configure:3182: result: no
```

**Comment by mistydemeo** [comment] 2015-08-27 17:27
Looks like a superenv bug, though I'm not immediately sure of the cause.

The shim scripts use this to set up the load path:

```
if RUBY_VERSION < "1.8.7"
  $:.unshift("#{ENV['HOMEBREW_PREFIX']}/Library/Homebrew")
  require 'extend/string'
  require 'vendor/backports/enumerator'
end
```

I see you have Tigerbrew installed outside `/usr/local`. Do you by any chance have the prefix and the repository in different locations?

**Comment by chdiza** [comment] 2015-08-27 17:47
>  Do you by any chance have the prefix and the repository in different locations?

I do, and I totally forgot about that.  Is that disallowed in Tigerbrew?

**Comment by mistydemeo** [comment] 2015-08-27 17:50
Nope, it's definitely allowed. That just confirms where the bug is; I used `HOMEBREW_PREFIX` to mean `HOMEBREW_REPOSITORY`, which isn't correct here.

**Comment by mistydemeo** [comment] 2015-08-27 17:53
Should be fixed. I also uploaded readline bottles.

**Closed** 2015-08-27 17:53 UTC

**Comment by chdiza** [comment] 2015-08-27 17:58
Thanks!

**Comment by mistydemeo** [comment] 2015-08-27 18:01
Let me know if that solves building from source for you!

**Comment by chdiza** [comment] 2015-08-27 18:06
Yup, works :)

**Comment by mistydemeo** [comment] 2015-08-27 18:14
Excellent!
