### ISSUE TITLE
subversion fails to find dyld

### ISSUE THREAD

**Issue by GXTX** [mistydemeo/tigerbrew#656] opened 2020-01-20 08:59 UTC
While installing `clang-format` on Leopard 10.5.8 PPC it installs a few dependencies including `subversion`, the bottle for `subversion` is missing `libmagic` producing the following error.

The workaround for this is to `brew install libmagic`.

```
==> Installing clang-format
==> Cloning http://llvm.org/svn/llvm-project/llvm/tags/google/testing/2015-07-31/
dyld: Library not loaded: /usr/local/lib/libmagic.1.dylib
  Referenced from: /usr/local/bin/svn
  Reason: image not found
Error: Failed to download resource "clang-format"
Failure while executing: svn checkout -q http://llvm.org/svn/llvm-project/llvm/tags/google/testing/2015-07-31/ /Users/dev/Library/Caches/Homebrew/clang-format--svn
```

**Comment by sevan** [comment] 2023-08-17 22:39
With an up to date Tigerbrew tree, try the  svn v1.14.2 update in PR #818

**Comment by GXTX** [comment] 2023-08-27 01:18
I no longer have a device to try this on. I will leave it up to maintainer if they want to close this issue.

**Comment by mistydemeo** [comment] 2023-08-31 04:25
This was caused by a bottle that linked against an undeclared dependency. Fixed now.

**Closed** 2023-08-31 04:24 UTC
