### ISSUE TITLE
zlib never updating and affecting other software

### ISSUE THREAD

**Issue by and3r00** [mistydemeo/tigerbrew#965] opened 2023-09-13 18:09 UTC
I'm unable to install zlib, git, openssh, and many other things for some reason. OSX Leopard 10.5.9

I installed the linked Xcode, tried to install the newer XQuartz, supposedly it did install, but it continues to show it as not installed.

I edited /etc/paths and moved /usr/local/bin to the top. I also added /usr/local/bin to my path.

https://gist.github.com/and3r00/2cb10c4d06c16be4393dd89982c98292

**Comment by mistydemeo** [comment] 2023-09-13 18:11
Can you try running `brew install zlib` first? It looks like it's getting confused about which zlib to use; it may help to get that installed first.

**Comment by mistydemeo** [comment] 2023-09-13 18:22
Can you confirm the output for `brew info openssh`? I want to make sure you're using a version where zlib is a dependency.

**Comment by and3r00** [comment] 2023-09-13 18:25
ajis-ibook-g4:~ test1$ brew info openssh
openssh: stable 9.4p1
OpenBSD freely-licensed SSH connectivity tools
https://www.openssh.com/
Not installed
From: /usr/local/Library/Formula/openssh.rb
==> Dependencies
Build: pkg-config ✔
Required: ldns ✔, openssl ✔, zlib ✔

**Comment by sevan** [comment] 2023-09-13 20:09
What does `brew info zlib` say?

**Comment by and3r00** [comment] 2023-09-13 20:15
ajis-ibook-g4:~ test1$ brew info zlib
zlib: stable 1.3
General-purpose lossless data-compression library
http://www.zlib.net/

This formula is keg-only.
OS X already provides this software and installing another version in
parallel can cause all kinds of trouble.

/usr/local/Cellar/zlib/1.3 (10 files, 424K)
  Built from source
From: /usr/local/Library/Formula/zlib.rb
==> Caveats
This formula is keg-only, which means it was not symlinked into /usr/local.

OS X already provides this software and installing another version in
parallel can cause all kinds of trouble.

Generally there are no consequences of this for you. If you build your
own software and it requires this formula, you'll need to add to your
build variables:

    LDFLAGS:  -L/usr/local/opt/zlib/lib
    CPPFLAGS: -I/usr/local/opt/zlib/include

**Comment by and3r00** [comment] 2023-09-13 20:27
I'm also getting this error on many different installs. I am not sure if it is unrelated.
```
brew install readline
==> Downloading https://ftpmirror.gnu.org/readline/readline-8.2.tar.gz
Already downloaded: /Users/test1/Library/Caches/Homebrew/readline-8.2.tar.gz
==> ./configure --prefix=/usr/local/Cellar/readline/8.2 --enable-multibyte
==> make install
Last 15 lines from /Users/test1/Library/Logs/Homebrew/readline/02.make:
2023-09-13 13:26:26 -0700

make
install

/bin/sh ./support/mkinstalldirs /usr/local/Cellar/readline/8.2/include \
		/usr/local/Cellar/readline/8.2/include/readline /usr/local/Cellar/readline/8.2/lib \
		/usr/local/Cellar/readline/8.2/share/info /usr/local/Cellar/readline/8.2/share/man/man3 /usr/local/Cellar/readline/8.2/share/doc/readline \
		/usr/local/Cellar/readline/8.2/lib/pkgconfig
mkdir -p -- /usr/local/Cellar/readline/8.2/include /usr/local/Cellar/readline/8.2/include/readline /usr/local/Cellar/readline/8.2/lib /usr/local/Cellar/readline/8.2/share/info /usr/local/Cellar/readline/8.2/share/man/man3 /usr/local/Cellar/readline/8.2/share/doc/readline /usr/local/Cellar/readline/8.2/lib/pkgconfig
rm -f readline.o
gcc-4.2 -std=gnu99 -c  -DHAVE_CONFIG_H   -I. -I.  -DRL_LIBRARY_VERSION='"8.2"' -DBRACKETED_PASTE_DEFAULT=1 -g -O2 -Wno-parentheses -Wno-format-security -Wno-tautological-constant-out-of-range-compare readline.c
cc1: error: unrecognized command line option "-Wno-tautological-constant-out-of-range-compare"
make: *** [readline.o] Error 1
```

**Comment by sevan** [comment] 2023-09-13 20:30
hmm, are you starting from scratch or trying to bring an old instance of Tigerbrew up to date?
The reason I ask is that I have just dusted off an iBook running 10.5.8 and on a fresh checkout of the Tigerbrew repo, `brew install -v git` reports

```
==> Installing dependencies for git: xz, gettext, perl, makedepend, curl-ca-bundle, openssl, pkg-config, ldns, zlib, openssh, curl, make
```

> I'm unable to install zlib, git, openssh, and many other things for some reason. OSX Leopard **10.5.9**

Did you mean 10.5.8 or you're running Sorbet Leopard? (10.5.9)

**Comment by and3r00** [comment] 2023-09-13 20:31
I am running Sorbet. 10.5.9.

**Comment by and3r00** [comment] 2023-09-13 20:35
Fresh install on Sorbet.

**Comment by sevan** [comment] 2023-09-13 20:39
download and extract a copy of the [Tigerbrew repo](https://github.com/mistydemeo/tigerbrew/archive/refs/heads/master.zip) in your Downloads folder.
`cd ~/Downloads/tigerbrew-master`
`./bin/brew install -v git`

Do you get the same `Installing dependencies for git:` line as I posted earlier?

**Comment by and3r00** [comment] 2023-09-13 20:54
I did what you said and it's continuing to run and install stuff. 

I used the[ install file ](https://raw.github.com/mistydemeo/tigerbrew/go/install)linked on the homepage to do my install. I didn't download the master like you linked. I did have to edit the https to http at the time due to it failing on encryption.

It's still working as I post this.

The specific dependencies it required I didn't get a chance to look at as I expected it to not work like before when I ran it, but it continued running the install..

**Comment by sevan** [comment] 2023-09-13 23:54
Reproduced the issue on stock 10.5.8 Leopard. Fix in the PR.

**Comment by mistydemeo** [comment] 2023-09-13 23:54
I've just merged the fix.

**Comment by sevan** [comment] 2023-09-13 23:54
Thanks :)

**Comment by and3r00** [comment] 2023-09-13 23:58
Not sure if this is necessary anymore but that command finally finished on an error with openssh. 

But to answer your question I did re-run it temporarily to get the answer.

```
./bin/brew install -v git
==> Installing dependencies for git: openssh, curl, make
==> Installing git dependency: openssh
```

Since this has been fixed maybe I can just delete everything and start with a new build and re-download the master.

**Comment by mistydemeo** [comment] 2023-09-14 00:02
Sorry for the inconvenience with all this! I'll close this for now assuming it's been fixed, but please let me know if it happens again on a rebuild.

You can also temporarily replace the `Library/Formula/openssh.rb` with the version from master if you don't want to replace all of Homebrew.

**Closed by mistydemeo** 2023-09-14 00:02 UTC
