### ISSUE TITLE
On Tiger PPC can't brew git because of sha256 issues

### ISSUE THREAD

**Issue by chdiza** [mistydemeo/tigerbrew#316] opened 2015-04-18 16:04 UTC
Tiger PPC here.  I tried brewing git, and most of it went through until I got here:
```
==> Verifying git--man-2.3.5.tar.xz checksum
/usr/local/Library/Homebrew/debrew.rb:11:in `raise'
SHA2NotInstalledError: SHA2NotInstalledError
1. raise
2. ignore
3. backtrace
4. irb
5. shell
Choose an action: 2
sh: line 1: /usr/local/opt/sha2/bin/sha2: No such file or directory
/usr/local/Library/Homebrew/extend/pathname.rb:287:in `sha256_homebrew_sha2'
```
At the beginning of the brewing, I got this:
```
==> Verifying git-2.3.5.tar.xz checksum
/usr/local/Library/Homebrew/build.rb (Formulary::FormulaLoader): loading /usr/local/Library/Formula/sha2.rb
Warning: No native sha256 available; falling back to slower Python implementation.
It is recommended to:
  brew install sha2
```
I didn't brew sha2, because the wording suggests that doing so is optional.  There must be some issue with the Python fallback, I guess.

**Comment by mistydemeo** [comment] 2015-05-03 20:15
Just to check, can you still repro this? What's the output of `brew info sha2`?

**Comment by mistydemeo** [comment] 2015-05-03 20:18
What's the specific `brew` command you ran?

**Comment by chdiza** [comment] 2015-05-04 02:04
I cannot still repro (not on git 2.4; the original report was on 2.3.5). (The bug ~~is~~ was that the Python handler for sha256 does not work).  However, it took Python about ten minutes at 100% CPU to verify the sha256 checksum on git.

I use `brew install -d git`.

**Comment by mistydemeo** [comment] 2015-05-04 02:08
>  However, it took Python about ten minutes at 100% CPU to verify the sha256 checksum on git.

This is, unfortunately, accurate. The Python code is *extremely slow*. :/  I don't think there are meaningful speedups to be had; the slowness is coming from the interpreter. I had similar performance with a pure-Ruby version I was writing.

Since the original problem isn't occurring, I'm provisionally closing this. Do you think the wording of the error could be better worded to make it clear "you *really* should install sha2"?

**Comment by chdiza** [comment] 2015-05-04 02:10
Whoops, i spoke too soon :(

When I tried it again, it got all the way down to the git manpages part and *then* gave the error message I alluded to above.

**Comment by chdiza** [comment] 2015-05-04 02:12
For some reason Tigerbrew is forgetting that it's supposed to be using the Python implementation (when it's already been detected that `sha2` isn't brewed.

**Comment by mistydemeo** [comment] 2015-05-04 02:12
Iiinteresting. So it only reproduces when doing the resource, not the main tarball? That's helpful, thanks!

**Comment by mistydemeo** [comment] 2015-05-04 02:19
Oh, I see what's going on.

I'm using exceptions as flow control here (naughty, I know). Tigerbrew first tries to call the function that runs the native sha2; this raises an `SHA2NotInstalledError` exception if sha2 is not installed, which in your case it isn't. The function calling it catches that specific exception if it occurs, and dispatches to the Python sha2 function. debrew overrides the standard Ruby `raise` handler to allow exceptions to be interrupted when they occur. That means the exception doesn't bubble up to the caller before it gets sent to you; since you told Tigerbrew to ignore it, it proceeds with the `sha256_homebrew_sha2` function even though sha2 isn't installed.

If you use option 1, "raise", it should work as expected.

**Comment by chdiza** [comment] 2015-05-04 04:27
> So it only reproduces when doing the resource, not the main tarball? That's helpful, thanks!

That's what happened this time; the first time(s) it was the main tarball.

> since you told Tigerbrew to ignore it,

I'm confused; what did I tell TB to ignore?  All I did was `install -d git`.  I thought the `-d` is supposed to do the opposite of ignoring errors.

> If you use option 1, "raise", it should work as expected.

Yes, selecting "raise" will then proceed, though I had to do it once for each resource.

**Comment by chdiza** [comment] 2015-05-04 04:37
> Do you think the wording of the error could be better worded to make it clear "you really should install sha2"?

I'm thinking maybe it should be "must".

In fact, I'm wondering if maybe we should just vendor pre-built `sha2`, so that it's just automatically there without having to even `brew install sha2`.  If we don't do this, then the installer script should finish with a caveat instructing the user to `brew install sha2` immediately.

Or perhaps there could be a `sha2` dependency that gets triggered by any formula which has a `sha256`.  (Something like how any formula whose tarball ends in `.xz` triggers an xz dependency).

Here is another concern: on the Tiger box in question, I already had `openssl` brewed.  Shouldn't that have been opportunistically used?  Perhaps TB should go through the following checks: sha2?  If so, use it.  If not, then brewed-openssl?  If so, use it.  If not, Python implementation.

**Comment by mistydemeo** [comment] 2015-05-07 15:46
> Here is another concern: on the Tiger box in question, I already had openssl brewed. Shouldn't that have been opportunistically used?

I removed the openssl sha2 support because I didn't want to support multiple codepaths (and because sha2 is so fast to build), but maybe it's worth having more than one fallback just in case

**Comment by mistydemeo** [comment] 2015-05-07 15:47
> In fact, I'm wondering if maybe we should just vendor pre-built sha2, so that it's just automatically there without having to even brew install sha2.

Vendoring is a little iffier when it's a binary, but I guess if I produce a Tiger G3/i386 fat binary it should be compatible with all supported systems.

**Comment by chdiza** [comment] 2015-05-11 17:53
I'm thinking either the fat binary, or make every formula with a sha256 in it trigger a dependency on `sha2`.

That way, the brewer does not have to take any special steps, nor do we have to worry about where to put an special instructions.

**Comment by mistydemeo** [comment] 2015-05-11 18:03
You have a G3 Tiger Mac, right? Would you be able to test an sha2 binary for me if I built one?

**Comment by chdiza** [comment] 2015-05-11 18:28
No, it's a G4.

**Comment by mistydemeo** [comment] 2015-05-15 05:41
I have a branch up, `sha2`, which replaces the Python script and replaces it with a prebuilt ppc/i386 `sha2` binary. I haven't tested on G3, but seems fine on both G4 and Intel.

**Comment by chdiza** [comment] 2015-05-15 14:40
I'll test this when I next get my hands on my PPC box.  Sounds great!

**Comment by mistydemeo** [comment] 2015-05-21 15:41
Incorporated into the master branch as 7236ae968760c88fa8139f768cf3980bc0755ed3. Seems to be working well!

**Closed** 2015-05-30 04:27 UTC
