### ISSUE TITLE
brew reports error in postinstall.rb (10.4/G4)

### ISSUE THREAD

**Issue by dcwar** [mistydemeo/tigerbrew#323] opened 2015-05-03 02:33 UTC
On upgrading any package, brew reports that the post-install step didn't complete successfully. The error from ruby is:

/usr/local/Library/Homebrew/postinstall.rb:18:in `dump': instance of IO needed (TypeError)
	from /usr/local/Library/Homebrew/postinstall.rb:18

Sample console output for youtube-dl: 

https://gist.github.com/dcwar/d5c312eb52553aa419b1

**Comment by mistydemeo** [comment] 2015-05-03 02:54
Should be fixed now! This was caused by some of the sandbox code in Homebrew, which I've had to roll back due to not being compatible with older Rubies.

**Closed** 2015-05-03 02:53 UTC

**Comment by dcwar** [comment] 2015-05-03 03:18
Ahhh - interesting! Thank you so much!!
