### ISSUE TITLE
several problems with libconfig

### ISSUE THREAD

**Issue by pk2061** [mistydemeo/tigerbrew#786] opened 2022-03-25 15:34 UTC
I tried to install the libconfig package on my iMac G3 running 10.4 Tiger.

I used "brew install libconfig.

**1. Extracting the archive libconfig-1.7.2.tar.gz:**
I noticed that it crashed before or while running ./configure.
It seems that the file libconfig-1.7.2.tar.gz which is downloaded can't be extracted normally.

So I tried to extract the archive manually: 
```
imac-g3:~/Library/Caches/Homebrew jan$ tar -xf libconfig-1.7.2.tar.gz
tar: This does not look like a tar archive
tar: Skipping to next header
tar: Archive contains obsolescent base-64 headers
tar: Read 7331 bytes from libconfig-1.7.2.tar.gz
tar: Error exit delayed from previous errors
imac-g3:~/Library/Caches/Homebrew jan$ 
```

_Does this affect only me, might this be a general problem with archive?_ 

**What I did to overcome this:**
So I downloaded the libconfig-1.7.2.tar.gz archive with my modern iMac, extracted the archive onto my modern mac.
Then I created the archive manually on my modern iMac:
`Jans-iMac:Downloads jan$ tar -czf libconfig-1.7.2.tar.gz libconfig-1.7.2 `
Next I copied the newly created libconfig-1.7.2.tar.gz into the /Users/jan/Library/Caches/Homebrew/-folder on my "old" iMac G3.
After I updated the SHA256 hash I ran  "brew install libconfig again" .

 **2. GCC is not recognized correctly:**
When running brew install I get this output:
```
==> ./configure --prefix=/usr/local/Cellar/libconfig/1.7.2
Last 15 lines from /Users/jan/Library/Logs/Homebrew/libconfig/01.configure:
checking for a thread-safe mkdir -p... aux-build/install-sh -c -d
checking for gawk... no
checking for mawk... no
checking for nawk... no
checking for awk... awk
checking whether make sets $(MAKE)... yes
checking whether make supports nested variables... yes
checking whether make supports nested variables... (cached) yes
configure: libconfig - made with pride in Colorado
checking for style of include used by make... GNU
checking for gcc... /usr/local/bin/gcc-4.2
checking whether the C compiler works... no
configure: error: in `/private/tmp/libconfig20220325-7226-13zcace/libconfig-1.7.2':
configure: error: C compiler cannot create executables
See `config.log' for more details
```

Do you have any suggestion how to proceed?
Thanks in advance for your help!

**Comment by mistydemeo** [comment] 2022-03-26 03:44
Can you please give me a copy of the `config.log` from the failed build? That'll help me.

**Comment by pk2061** [comment] 2022-03-26 11:23
Thank you for looking into this.
I attached both the config.log and the 01.configure output.

Have a nice Weekend! :)
Best regards

[01.configure.txt](https://github.com/mistydemeo/tigerbrew/files/8355265/01.configure.txt)
[config.log](https://github.com/mistydemeo/tigerbrew/files/8355266/config.log)

**Comment by Sofia61819** [comment] 2022-03-30 03:10
[Okok](okok) #
Duplicate of #

**Comment by Sofia61819** [comment] 2022-03-30 03:10
[]() 

> ``

**Comment by mistydemeo** [comment] 2022-03-30 03:26
> /usr/bin/ld: can't locate file for: -lgcc_s.10.4

Huh. That's strange. Does `/usr/lib/libgcc_s.10.4.dylib` exist, or any other file with a similar name?

**Comment by pk2061** [comment] 2022-03-30 20:43
Update:
Thanks for the hint!
 I managed to finde the file libgcc_s.10.4.dylib in /Developer/SDKs/MacOSX10.4u.sdk/usr/lib - so I just copied it to /usr/lib/ and the build went through without any more problems.

Thanks for the help!

**Comment by sevan** [comment] 2023-08-20 21:46
Looks like it was solved.

**Closed** 2023-08-20 23:18 UTC
