### ISSUE TITLE
Pianobar failed to build on Mac OS 10.4.11

### ISSUE THREAD

**Issue by The48thRonin** [mistydemeo/tigerbrew#312] opened 2015-04-07 02:39 UTC
This is the gist requested by the troubleshooting page.
https://gist.github.com/2f13cf6939f59f7806f2.git
I have had Pianobar working before (on the same OS with tigerbrew), but reinstalled my OS to get the OS9 drivers for a game I picked up. After the reinstall, I installed Xcode command line tools, got Tigerbrew working, and tried to install Pianobar, where I ran into the unfortunate error messages above. I have checked 'brew  doctor' and it outputs 'Your system is ready to brew.'
Please don't hate if I posted in the wrong area, this is my first time submitting an issue. If there is any more info I need to provide, then please let me know, I will gladly provide it.

**Comment by mistydemeo** [comment] 2015-04-13 16:20
Looks like it's trying to use a compiler flag that wasn't defined in GCC 4.0:

> cc1: error: unrecognized command line option "-Wno-error=deprecated-declarations"

I'll poke at this tonight.

**Comment by The48thRonin** [comment] 2015-05-07 01:15
Ah ok... Not sure what that means but I'll try to research as well. (Sorry for the delay, school and stuff).

**Comment by mistydemeo** [comment] 2015-05-07 01:23
Sorry, lost track of this. I think this is actually fixed on Leopard but I'll fix it for Tiger.

**Comment by The48thRonin** [comment] 2015-05-07 01:24
Ok thanks! I'll update it this weekend and try it out.

**Closed** 2015-05-07 06:14 UTC

**Comment by mistydemeo** [comment] 2015-05-07 06:15
I can't reproduce the original problem! However, I've gone ahead and built Altivec binaries of pianobar, so even if you can't build it yourself you can use those. If you `brew update` and `brew install pianobar`, assuming you're on G4 or higher, you should be okay.
