### ISSUE TITLE
cmake build fails due to error with sha256 while verifying patch (10.4/G4)

### ISSUE THREAD

**Issue by dcwar** [mistydemeo/tigerbrew#340] opened 2015-06-20 03:10 UTC
Attempting to reinstall cmake fails when attempting to verify a patch, saying (line 40 console output) "/usr/local/Library/Homebrew/vendor/sha256: No such file or directory". SHA256 does in fact exist so…? Not sure what to make of that.

Console Output:
https://gist.github.com/dcwar/280a12f9ec7a48731098

brew config:
https://gist.github.com/dcwar/12868da4625eca2bf780

**Comment by mistydemeo** [comment] 2015-06-20 03:26
If you `cd` into /usr/local, what's the output of `git status`? Are the permissions on that file OK?

**Comment by dcwar** [comment] 2015-06-20 04:01
git status reports: "On branch master nothing to commit, working directory clean"

Permissions on vendored sha256 are -rwxr-xr-x.  o_O

**Comment by mistydemeo** [comment] 2015-06-20 04:21
What's curious to me is that it clearly succeeded at hashing an earlier file!

What about `brew fetch -fs cmake`?

**Comment by dcwar** [comment] 2015-06-20 04:29
Output follows - line 39?

https://gist.github.com/dcwar/a0d4a0ad4afa407d1888

**Comment by mistydemeo** [comment] 2015-06-20 04:31
Oh, of course: it's not complaining that `sha256` is missing, rather the `sha256` tool is complaining that the file it's trying to hash is missing.

**Comment by mistydemeo** [comment] 2015-06-20 04:31
Does `/Library/Caches/Homebrew/cmake--patch-147854010874cd68289e3ca203399d5c149287167bca0b67f9c5677f0ee22eb8.git;a=commitdiff_plain;h=2ecf168f` exist under that exact name?

**Comment by dcwar** [comment] 2015-06-20 04:33
Oy. Yes, indeed it does exist under that exact name!

**Comment by mistydemeo** [comment] 2015-06-20 04:46
OK, I can reproduce in the master branch - I couldn't in the branch in which I'd been working because of a new version of cmake, oops.

Fixed in e05155b; this'll be merged in with the updates branch later today or early tomorrow. I'll have a cmake binary package at the same time!

**Comment by dcwar** [comment] 2015-06-20 04:49
Oooh! Thank you!!

**Comment by mistydemeo** [comment] 2015-06-20 07:58
Fixed, and binary package is up!

**Closed** 2015-06-20 07:57 UTC
